# Redirection HTTP -> HTTPS
ser {
    listen 80;
    server_name trackmystage.cbodev.fr;
    return 301 https://$host$request_uri;
}

# Serveur HTTPS
server {
    listen 443 ssl;
    server_name trackmystage.cbodev.fr;

    ssl_certificate /etc/letsencrypt/live/nomApp.nomdomaine.fr/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/nomApp.nomdomaine.fr/privkey.pem;

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://backend:8000;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    }
}